version: '3.8'

services:

  postgres:
    restart: always
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./docker.sql:/docker-entrypoint-initdb.d/docker.sql

  spring_service:
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: spring
    ports:
     - "8080:8080"
    environment:
      HTTP_ADDR: ":9090"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true