spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  tomcat:
    max-threads: 1000
    min-spare-threads: 40

eva:
  regex: "(\\^\\.?\\*?)([\\p{L}\\d]*)(\\[?[\\p{L}\\d]*]?)([\\p{L}\\d]*)(\\.?\\*?\\$)"
  minRegexSize: 1
  maxResponseList: 1000