version: '3'
services:
  my-app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
#    depends_on:
#      - db
#  db:
#    image: mysql:latest
#    environment:
#      MYSQL_ROOT_PASSWORD: example
#      MYSQL_DATABASE: mydatabase
#      MYSQL_USER: myuser
#      MYSQL_PASSWORD: mypassword
