version: '3.8'

services:

#  postgres:
#    restart: always
#    image: postgres:latest
#    ports:
#      - 5433:5432
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=callback
#    volumes:
#      - ./internal/pg/data:/var/lib/postgresql/data

  spring_service:
#    depends_on:
#      - postgres
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: spring
    ports:
     - "8080:8081"
#    environment:
#      HTTP_ADDR: ":9090"
#    volumes:
#      - .m2:/root/.m2
#    stdin_open: true
#    tty: true