openapi: "3.0.0"
info:
  description: "Test Service"
  version: "4"
  title: "org.test.spring.service"
servers:
  - url: "/rest/org.test.spring.service"
paths:
  /hello:
    get:
      tags:
        - MainService
      summary: Hello string
      description: Hello string
      operationId: hello
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloDTO'
  /view:
    get:
      tags:
        - ViewService
      summary: Get view
      description: Get view by id
      operationId: getView
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ViewDTO'
    post:
      tags:
        - ViewService
      summary: Crete new view
      operationId: createView
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ViewDTO'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ViewDTO'
    put:
      summary: Update view
      operationId: updateView
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ViewDTO'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ViewDTO'
    delete:
      summary: Delete view
      operationId: deleteView
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: OK
  /view/list:
    get:
      summary: Get all Views
      operationId: getViews
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ViewDTO'
components:
  schemas:
    HelloDTO:
      type: object
      properties:
        message:
          type: string
    ViewDTO:
      type: "object"
      description: View for event data
      required:
        - views
      properties:
        id:
          type: integer
          format: int64
        views:
          type: string
    View:
      type: "object"
      description: View for viewDto
      required:
        - views
      properties:
        x:
          type: string
        xxx:
          type: string